export const PERMISSION_GROUPS = [
  {
    key: "dashboard",
    label: "Dashboard",
    permissions: [
      { key: "dashboard.view", label: "View Dashboard", action: "view" },
      { key: "dashboard.analytics", label: "View Analytics", action: "view" },
    ],
  },
  {
    key: "orders",
    label: "Orders",
    permissions: [
      { key: "orders.view", label: "View Orders", action: "view" },
      { key: "orders.create", label: "Create Orders", action: "create" },
      { key: "orders.edit", label: "Edit Orders", action: "edit" },
      { key: "orders.delete", label: "Delete Orders", action: "delete" },
      { key: "orders.cancel", label: "Cancel Orders", action: "manage" },
      { key: "orders.print", label: "Print Orders", action: "manage" },
      { key: "orders.changeStatus", label: "Change Order Status", action: "manage" },
      { key: "orders.refund", label: "Refund Orders", action: "manage" },
      { key: "orders.export", label: "Export Orders", action: "manage" },
    ],
  },
  {
    key: "products",
    label: "Products",
    permissions: [
      { key: "products.view", label: "View Products", action: "view" },
      { key: "products.create", label: "Create Products", action: "create" },
      { key: "products.edit", label: "Edit Products", action: "edit" },
      { key: "products.delete", label: "Delete Products", action: "delete" },
      { key: "products.import", label: "Import Products", action: "manage" },
      { key: "products.export", label: "Export Products", action: "manage" },
    ],
  },
  {
    key: "categories",
    label: "Categories",
    permissions: [
      { key: "categories.view", label: "View Categories", action: "view" },
      { key: "categories.create", label: "Create Categories", action: "create" },
      { key: "categories.edit", label: "Edit Categories", action: "edit" },
      { key: "categories.delete", label: "Delete Categories", action: "delete" },
    ],
  },
  {
    key: "kitchen",
    label: "Kitchen",
    permissions: [
      { key: "kitchen.view", label: "View Kitchen", action: "view" },
      { key: "kitchen.accept", label: "Accept Orders", action: "manage" },
      { key: "kitchen.prepare", label: "Mark Preparing", action: "manage" },
      { key: "kitchen.markReady", label: "Mark Ready", action: "manage" },
      { key: "kitchen.complete", label: "Complete Orders", action: "manage" },
      { key: "kitchen.print", label: "Print Kitchen Reports", action: "manage" },
    ],
  },
  {
    key: "waiter",
    label: "Waiter",
    permissions: [
      { key: "waiter.view", label: "View Waiter Management", action: "view" },
      { key: "waiter.own", label: "Personal Waiter Panel", action: "view" },
      { key: "waiter.callWaiter", label: "Call Waiter Requests", action: "manage" },
      { key: "waiter.billRequest", label: "Bill Requests", action: "manage" },
      { key: "waiter.customerRequests", label: "Customer Requests", action: "manage" },
      { key: "waiter.manageRequests", label: "Manage All Requests", action: "manage" },
      { key: "waiter.processDeliveries", label: "Process Deliveries", action: "manage" },
      { key: "waiter.viewAssignedTables", label: "View Assigned Tables", action: "view" },
      { key: "waiter.requestAssistance", label: "Request Assistance", action: "manage" },
    ],
  },
  {
    key: "host",
    label: "Host",
    permissions: [
      { key: "host.view", label: "View Host Dashboard", action: "view" },
      { key: "host.manageArrivals", label: "Manage Arrivals", action: "manage" },
      { key: "host.manageQueue", label: "Manage Queue", action: "manage" },
      { key: "host.assignTables", label: "Assign Tables", action: "manage" },
      { key: "host.createReservations", label: "Create Reservations", action: "create" },
      { key: "host.viewFloorPlan", label: "View Floor Plan", action: "view" },
    ],
  },
  {
    key: "customers",
    label: "Customers",
    permissions: [
      { key: "customers.view", label: "View Customers", action: "view" },
      { key: "customers.create", label: "Create Customers", action: "create" },
      { key: "customers.edit", label: "Edit Customers", action: "edit" },
      { key: "customers.delete", label: "Delete Customers", action: "delete" },
      { key: "customers.export", label: "Export Customers", action: "manage" },
    ],
  },
  {
    key: "payments",
    label: "Payments",
    permissions: [
      { key: "payments.view", label: "View Payments", action: "view" },
      { key: "payments.process", label: "Process Payments", action: "manage" },
      { key: "payments.refund", label: "Refund Payments", action: "manage" },
      { key: "payments.export", label: "Export Payments", action: "manage" },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    permissions: [
      { key: "reports.view", label: "View Reports", action: "view" },
      { key: "reports.export", label: "Export Reports", action: "manage" },
      { key: "reports.financial", label: "Financial Reports", action: "manage" },
      { key: "reports.kitchen", label: "Kitchen Reports", action: "manage" },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    permissions: [
      { key: "inventory.view", label: "View Inventory", action: "view" },
      { key: "inventory.create", label: "Create Inventory", action: "create" },
      { key: "inventory.edit", label: "Edit Inventory", action: "edit" },
      { key: "inventory.delete", label: "Delete Inventory", action: "delete" },
      { key: "inventory.receive", label: "Receive Stock", action: "manage" },
      { key: "inventory.adjust", label: "Adjust Stock", action: "manage" },
      { key: "inventory.print", label: "Print Inventory", action: "manage" },
    ],
  },
  {
    key: "employees",
    label: "Employees",
    permissions: [
      { key: "employees.view", label: "View Employees", action: "view" },
      { key: "employees.create", label: "Create Employees", action: "create" },
      { key: "employees.edit", label: "Edit Employees", action: "edit" },
      { key: "employees.delete", label: "Delete Employees", action: "delete" },
      { key: "employees.assignRoles", label: "Assign Roles", action: "manage" },
    ],
  },
  {
    key: "roles",
    label: "Roles",
    permissions: [
      { key: "roles.view", label: "View Roles", action: "view" },
      { key: "roles.create", label: "Create Roles", action: "create" },
      { key: "roles.edit", label: "Edit Roles", action: "edit" },
      { key: "roles.delete", label: "Delete Roles", action: "delete" },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    permissions: [
      { key: "settings.view", label: "View Settings", action: "view" },
      { key: "settings.edit", label: "Edit Settings", action: "edit" },
      { key: "settings.system", label: "System Settings", action: "manage" },
    ],
  },
  {
    key: "reservations",
    label: "Reservations",
    permissions: [
      { key: "reservations.view", label: "View Reservations", action: "view" },
      { key: "reservations.create", label: "Create Reservations", action: "create" },
      { key: "reservations.edit", label: "Edit Reservations", action: "edit" },
      { key: "reservations.delete", label: "Delete Reservations", action: "delete" },
      { key: "reservations.approve", label: "Approve Reservations", action: "manage" },
    ],
  },
  {
    key: "notifications",
    label: "Notifications",
    permissions: [
      { key: "notifications.view", label: "View Notifications", action: "view" },
      { key: "notifications.manage", label: "Manage Notifications", action: "manage" },
    ],
  },
  {
    key: "suppliers",
    label: "Suppliers",
    permissions: [
      { key: "suppliers.view", label: "View Suppliers", action: "view" },
      { key: "suppliers.create", label: "Create Suppliers", action: "create" },
      { key: "suppliers.edit", label: "Edit Suppliers", action: "edit" },
      { key: "suppliers.delete", label: "Delete Suppliers", action: "delete" },
    ],
  },
  {
    key: "purchaseOrders",
    label: "Purchase Orders",
    permissions: [
      { key: "purchaseOrders.view", label: "View Purchase Orders", action: "view" },
      { key: "purchaseOrders.create", label: "Create Purchase Orders", action: "create" },
      { key: "purchaseOrders.edit", label: "Edit Purchase Orders", action: "edit" },
      { key: "purchaseOrders.delete", label: "Delete Purchase Orders", action: "delete" },
      { key: "purchaseOrders.approve", label: "Approve Purchase Orders", action: "manage" },
    ],
  },
  {
    key: "cleaning",
    label: "Cleaning",
    permissions: [
      { key: "cleaning.view", label: "View Cleaning Panel", action: "view" },
      { key: "cleaning.startCleaning", label: "Start Cleaning", action: "manage" },
      { key: "cleaning.completeCleaning", label: "Complete Cleaning", action: "manage" },
      { key: "cleaning.viewSchedule", label: "View Schedule", action: "view" },
    ],
  },
  {
    key: "activities",
    label: "Activities",
    permissions: [
      { key: "activities.view", label: "View Activities", action: "view" },
    ],
  },
  {
    key: "systemHealth",
    label: "System Health",
    permissions: [
      { key: "systemHealth.view", label: "View System Health", action: "view" },
    ],
  },
  {
    key: "auditLog",
    label: "Audit Log",
    permissions: [
      { key: "auditLog.view", label: "View Audit Log", action: "view" },
    ],
  },
  {
    key: "globalSearch",
    label: "Global Search",
    permissions: [
      { key: "globalSearch.view", label: "Use Global Search", action: "view" },
    ],
  },
]

export function getAllPermissionKeys() {
  return PERMISSION_GROUPS.flatMap((g) => g.permissions.map((p) => p.key))
}

export const ACTIONS = ["view", "create", "edit", "delete", "manage"]

export const ACTION_LABELS = {
  view: "View",
  create: "Create",
  edit: "Edit",
  delete: "Delete",
  manage: "Manage",
}

export const DEFAULT_ROLES = [
  {
    id: "role-owner",
    name: "Owner",
    description: "Full system access with all permissions",
    color: "bg-rose-100 text-rose-700 ring-rose-300",
    isSystem: true,
    permissions: getAllPermissionKeys(),
    branchAccess: "all",
    branchIds: [],
  },
  {
    id: "role-gm",
    name: "General Manager",
    description: "Access to all operational and management features",
    color: "bg-indigo-100 text-indigo-700 ring-indigo-300",
    isSystem: true,
    permissions: getAllPermissionKeys().filter((k) =>
      !["settings.system", "employees.delete", "employees.assignRoles", "roles.delete", "auditLog.view"].includes(k)
    ),
    branchAccess: "all",
    branchIds: [],
  },
  {
    id: "role-bm",
    name: "Branch Manager",
    description: "Full access within assigned branch",
    color: "bg-sky-100 text-sky-700 ring-sky-300",
    isSystem: true,
    permissions: getAllPermissionKeys().filter((k) =>
      ![
        "settings.system", "settings.edit",
        "employees.delete", "employees.assignRoles", "employees.create",
        "roles.view", "roles.create", "roles.edit", "roles.delete",
        "reports.financial", "reports.export",
        "payments.refund", "payments.export",
        "auditLog.view", "systemHealth.view",
        "globalSearch.view",
      ].includes(k)
    ),
    branchAccess: "assigned",
    branchIds: ["branch-1"],
  },
  {
    id: "role-cashier",
    name: "Cashier",
    description: "Process orders and payments at the counter",
    color: "bg-emerald-100 text-emerald-700 ring-emerald-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "orders.view", "orders.create", "orders.edit",
      "orders.changeStatus", "orders.print",
      "products.view", "categories.view",
      "customers.view", "customers.create",
      "payments.view", "payments.process",
    ],
    branchAccess: "assigned",
    branchIds: ["branch-1"],
  },
  {
    id: "role-kitchen",
    name: "Kitchen Staff",
    description: "View and manage orders in the kitchen",
    color: "bg-orange-100 text-orange-700 ring-orange-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "orders.view", "orders.changeStatus",
      "products.view",
      "kitchen.view", "kitchen.accept", "kitchen.prepare", "kitchen.markReady",
      "inventory.view",
    ],
    branchAccess: "assigned",
    branchIds: ["branch-1"],
  },
  {
    id: "role-waiter",
    name: "Waiter",
    description: "Take orders and serve customers",
    color: "bg-amber-100 text-amber-700 ring-amber-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "orders.view", "orders.create", "orders.edit", "orders.cancel",
      "products.view",
      "customers.view", "customers.create",
      "tables.view",
      "waiter.view", "waiter.own", "waiter.callWaiter", "waiter.billRequest", "waiter.customerRequests", "waiter.manageRequests", "waiter.processDeliveries", "waiter.viewAssignedTables", "waiter.requestAssistance",
    ],
    branchAccess: "assigned",
    branchIds: ["branch-1"],
  },
  {
    id: "role-delivery",
    name: "Delivery",
    description: "View and update delivery order status",
    color: "bg-lime-100 text-lime-700 ring-lime-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "orders.view", "orders.changeStatus",
    ],
    branchAccess: "assigned",
    branchIds: ["branch-1"],
  },
  {
    id: "role-accountant",
    name: "Accountant",
    description: "Financial reports and payment management",
    color: "bg-stone-100 text-stone-600 ring-stone-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "payments.view", "payments.refund", "payments.export",
      "reports.view", "reports.export", "reports.financial",
      "orders.view", "orders.refund",
      "customers.view",
    ],
    branchAccess: "all",
    branchIds: [],
  },
  {
    id: "role-inventory",
    name: "Inventory Manager",
    description: "Manage stock, ingredients, and purchase orders",
    color: "bg-teal-100 text-teal-700 ring-teal-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "inventory.view", "inventory.create", "inventory.edit",
      "inventory.receive", "inventory.adjust", "inventory.print",
      "products.view",
      "orders.view",
      "suppliers.view",
      "purchaseOrders.view", "purchaseOrders.create", "purchaseOrders.approve",
    ],
    branchAccess: "all",
    branchIds: [],
  },
  {
    id: "role-support",
    name: "Customer Support",
    description: "Handle customer inquiries and issues",
    color: "bg-violet-100 text-violet-700 ring-violet-300",
    isSystem: true,
    permissions: [
      "dashboard.view",
      "customers.view", "customers.create", "customers.edit",
      "orders.view", "orders.cancel", "orders.refund",
      "payments.view", "payments.refund",
    ],
    branchAccess: "all",
    branchIds: [],
  },
]

export const BRANCHES = [
  { id: "branch-1", name: "Downtown Branch" },
  { id: "branch-2", name: "Mall Branch" },
  { id: "branch-3", name: "Airport Branch" },
]

export const MOCK_USERS = [
  {
    id: "usr-1",
    name: "Ahmed Hassan",
    username: "ahmed.hassan",
    email: "ahmed@brunecoffee.com",
    phone: "+1 234 567 001",
    avatar: "",
    roleId: "role-owner",
    status: "active",
    lastLogin: "2026-07-01T09:23:00",
    createdAt: "2024-01-15T08:00:00",
    branchAccess: "all",
    branchIds: [],
    twoFactorEnabled: true,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-2",
    name: "Sarah Johnson",
    username: "sarah.j",
    email: "sarah@brunecoffee.com",
    phone: "+1 234 567 002",
    avatar: "",
    roleId: "role-gm",
    status: "active",
    lastLogin: "2026-07-01T10:15:00",
    createdAt: "2024-03-20T08:00:00",
    branchAccess: "all",
    branchIds: [],
    twoFactorEnabled: true,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-3",
    name: "Marco Rossi",
    username: "marco.r",
    email: "marco@brunecoffee.com",
    phone: "+1 234 567 003",
    avatar: "",
    roleId: "role-bm",
    status: "active",
    lastLogin: "2026-06-30T14:30:00",
    createdAt: "2024-06-01T08:00:00",
    branchAccess: "assigned",
    branchIds: ["branch-1"],
    twoFactorEnabled: false,
    failedLoginAttempts: 1,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-4",
    name: "Layla Mahmoud",
    username: "layla.m",
    email: "layla@brunecoffee.com",
    phone: "+1 234 567 004",
    avatar: "",
    roleId: "role-cashier",
    status: "active",
    lastLogin: "2026-07-01T08:45:00",
    createdAt: "2024-09-10T08:00:00",
    branchAccess: "assigned",
    branchIds: ["branch-1"],
    twoFactorEnabled: false,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-5",
    name: "Chef Omar",
    username: "omar.chef",
    email: "omar@brunecoffee.com",
    phone: "+1 234 567 005",
    avatar: "",
    roleId: "role-kitchen",
    status: "active",
    lastLogin: "2026-07-01T07:00:00",
    createdAt: "2024-02-14T08:00:00",
    branchAccess: "assigned",
    branchIds: ["branch-1"],
    twoFactorEnabled: false,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: ["inventory.edit", "inventory.receive", "reports.kitchen"],
    revokedPermissions: [],
  },
  {
    id: "usr-6",
    name: "Emma Wilson",
    username: "emma.w",
    email: "emma@brunecoffee.com",
    phone: "+1 234 567 006",
    avatar: "",
    roleId: "role-waiter",
    status: "locked",
    lastLogin: "2026-06-30T16:00:00",
    createdAt: "2024-11-05T08:00:00",
    branchAccess: "assigned",
    branchIds: ["branch-1"],
    twoFactorEnabled: false,
    failedLoginAttempts: 3,
    locked: true,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-7",
    name: "David Chen",
    username: "david.c",
    email: "david@brunecoffee.com",
    phone: "+1 234 567 007",
    avatar: "",
    roleId: "role-delivery",
    status: "active",
    lastLogin: "2026-06-29T18:30:00",
    createdAt: "2025-01-20T08:00:00",
    branchAccess: "assigned",
    branchIds: ["branch-1"],
    twoFactorEnabled: false,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-8",
    name: "Fatima Al-Rashid",
    username: "fatima.ar",
    email: "fatima@brunecoffee.com",
    phone: "+1 234 567 008",
    avatar: "",
    roleId: "role-accountant",
    status: "active",
    lastLogin: "2026-07-01T11:00:00",
    createdAt: "2024-08-12T08:00:00",
    branchAccess: "all",
    branchIds: [],
    twoFactorEnabled: true,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-9",
    name: "James Miller",
    username: "james.m",
    email: "james@brunecoffee.com",
    phone: "+1 234 567 009",
    avatar: "",
    roleId: "role-inventory",
    status: "locked",
    lastLogin: "2026-06-28T09:15:00",
    createdAt: "2024-07-01T08:00:00",
    branchAccess: "all",
    branchIds: [],
    twoFactorEnabled: false,
    failedLoginAttempts: 5,
    locked: true,
    extraPermissions: [],
    revokedPermissions: [],
  },
  {
    id: "usr-10",
    name: "Nora Williams",
    username: "nora.w",
    email: "nora@brunecoffee.com",
    phone: "+1 234 567 010",
    avatar: "",
    roleId: "role-support",
    status: "inactive",
    lastLogin: "2026-06-15T13:00:00",
    createdAt: "2025-03-01T08:00:00",
    branchAccess: "all",
    branchIds: [],
    twoFactorEnabled: false,
    failedLoginAttempts: 0,
    locked: false,
    extraPermissions: [],
    revokedPermissions: [],
  },
]

export const AUDIT_LOGS = [
  { id: "log-1", userId: "usr-1", userName: "Ahmed Hassan", action: "Updated system settings", module: "Settings", date: "2026-07-01T10:30:00", ip: "192.168.1.10", device: "Chrome / macOS", status: "success" },
  { id: "log-2", userId: "usr-2", userName: "Sarah Johnson", action: "Modified product #1042", module: "Products", date: "2026-07-01T10:15:00", ip: "192.168.1.11", device: "Firefox / Windows", status: "success" },
  { id: "log-3", userId: "usr-4", userName: "Layla Mahmoud", action: "Processed payment for order ORD-1056", module: "Payments", date: "2026-07-01T09:45:00", ip: "192.168.1.12", device: "Safari / iPad", status: "success" },
  { id: "log-4", userId: "usr-3", userName: "Marco Rossi", action: "Attempted to access financial reports", module: "Analytics", date: "2026-07-01T09:30:00", ip: "192.168.1.13", device: "Chrome / Android", status: "denied" },
  { id: "log-5", userId: "usr-1", userName: "Ahmed Hassan", action: "Created new user Emma Wilson", module: "Employees", date: "2026-06-30T16:00:00", ip: "192.168.1.10", device: "Chrome / macOS", status: "success" },
  { id: "log-6", userId: "usr-5", userName: "Chef Omar", action: "Updated order status ORD-1050 to Ready", module: "Orders", date: "2026-06-30T14:22:00", ip: "192.168.1.14", device: "Chrome / Windows", status: "success" },
  { id: "log-7", userId: "usr-9", userName: "James Miller", action: "Adjusted stock for Espresso beans", module: "Inventory", date: "2026-06-30T11:00:00", ip: "192.168.1.15", device: "Chrome / macOS", status: "success" },
  { id: "log-8", userId: "usr-6", userName: "Emma Wilson", action: "Failed login attempt #3", module: "Auth", date: "2026-06-30T10:30:00", ip: "192.168.1.16", device: "Safari / iPhone", status: "failed" },
  { id: "log-9", userId: "usr-2", userName: "Sarah Johnson", action: "Exported monthly sales report", module: "Reports", date: "2026-06-30T09:00:00", ip: "192.168.1.11", device: "Firefox / Windows", status: "success" },
  { id: "log-10", userId: "usr-8", userName: "Fatima Al-Rashid", action: "Processed refund for order ORD-1048", module: "Payments", date: "2026-06-29T15:45:00", ip: "192.168.1.17", device: "Chrome / macOS", status: "success" },
  { id: "log-11", userId: "usr-1", userName: "Ahmed Hassan", action: "Changed role permissions for Cashier", module: "Settings", date: "2026-06-29T14:00:00", ip: "192.168.1.10", device: "Chrome / macOS", status: "success" },
  { id: "log-12", userId: "usr-10", userName: "Nora Williams", action: "Created customer support ticket #1023", module: "Customers", date: "2026-06-28T12:30:00", ip: "192.168.1.18", device: "Chrome / Windows", status: "success" },
  { id: "log-13", userId: "usr-7", userName: "David Chen", action: "Marked order ORD-1045 as Delivered", module: "Orders", date: "2026-06-28T11:15:00", ip: "192.168.1.19", device: "Chrome / Android", status: "success" },
  { id: "log-14", userId: "usr-3", userName: "Marco Rossi", action: "Logged out", module: "Auth", date: "2026-06-28T10:00:00", ip: "192.168.1.13", device: "Chrome / Android", status: "success" },
  { id: "log-15", userId: "usr-1", userName: "Ahmed Hassan", action: "Enabled maintenance mode", module: "System", date: "2026-06-27T23:00:00", ip: "192.168.1.10", device: "Chrome / macOS", status: "success" },
]
